import { Application, Shortcut, ShortcutStore } from '../types/shortcuts';

const macOS: Application = {
  id: 'macos',
  name: 'macOS',
  icon: '🍎', // We can replace with actual icon path later
};

const defaultShortcuts: Record<string, Shortcut> = {
  'macos-copy': {
    id: 'macos-copy',
    name: 'Copy',
    keys: '⌘C',
    application: 'macos',
    isGlobal: true,
    description: 'Copy selected content to clipboard',
    tags: ['system', 'clipboard'],
  },
  'macos-paste': {
    id: 'macos-paste',
    name: 'Paste',
    keys: '⌘V',
    application: 'macos',
    isGlobal: true,
    description: 'Paste content from clipboard',
    tags: ['system', 'clipboard'],
  },
  'macos-cut': {
    id: 'macos-cut',
    name: 'Cut',
    keys: '⌘X',
    application: 'macos',
    isGlobal: true,
    description: 'Cut selected content to clipboard',
    tags: ['system', 'clipboard'],
  },
  'macos-save': {
    id: 'macos-save',
    name: 'Save',
    keys: '⌘S',
    application: 'macos',
    isGlobal: true,
    description: 'Save current document',
    tags: ['system', 'file'],
  },
  'macos-undo': {
    id: 'macos-undo',
    name: 'Undo',
    keys: '⌘Z',
    application: 'macos',
    isGlobal: true,
    description: 'Undo last action',
    tags: ['system', 'edit'],
  },
  'macos-redo': {
    id: 'macos-redo',
    name: 'Redo',
    keys: '⌘⇧Z',
    application: 'macos',
    isGlobal: true,
    description: 'Redo last action',
    tags: ['system', 'edit'],
  },
  'macos-find': {
    id: 'macos-find',
    name: 'Find',
    keys: '⌘F',
    application: 'macos',
    isGlobal: true,
    description: 'Find in document',
    tags: ['system', 'search'],
  },
  'macos-find-next': {
    id: 'macos-find-next',
    name: 'Find Next',
    keys: '⌘G',
    application: 'macos',
    isGlobal: true,
    description: 'Find next occurrence',
    tags: ['system', 'search'],
  },
  'macos-find-prev': {
    id: 'macos-find-prev',
    name: 'Find Previous',
    keys: '⌘⇧G',
    application: 'macos',
    isGlobal: true,
    description: 'Find previous occurrence',
    tags: ['system', 'search'],
  },
  'macos-select-all': {
    id: 'macos-select-all',
    name: 'Select All',
    keys: '⌘A',
    application: 'macos',
    isGlobal: true,
    description: 'Select all content',
    tags: ['system', 'edit'],
  },
  'macos-new': {
    id: 'macos-new',
    name: 'New',
    keys: '⌘N',
    application: 'macos',
    isGlobal: true,
    description: 'Create new document',
    tags: ['system', 'file'],
  },
  'macos-open': {
    id: 'macos-open',
    name: 'Open',
    keys: '⌘O',
    application: 'macos',
    isGlobal: true,
    description: 'Open document',
    tags: ['system', 'file'],
  },
  'macos-print': {
    id: 'macos-print',
    name: 'Print',
    keys: '⌘P',
    application: 'macos',
    isGlobal: true,
    description: 'Print document',
    tags: ['system', 'file'],
  },
  'macos-minimize': {
    id: 'macos-minimize',
    name: 'Minimize',
    keys: '⌘M',
    application: 'macos',
    isGlobal: true,
    description: 'Minimize window',
    tags: ['system', 'window'],
  },
  'macos-close': {
    id: 'macos-close',
    name: 'Close',
    keys: '⌘W',
    application: 'macos',
    isGlobal: true,
    description: 'Close window',
    tags: ['system', 'window'],
  },
};

export const initialStore: ShortcutStore = {
  applications: {
    macos: macOS,
  },
  shortcuts: defaultShortcuts,
}; 